### PR TITLE
Add fixed shape tensor

### LINKED ISSUE #3: Add fixed shape tensor

### PR DESCRIPTION
**Pull request by Alex-PLACET**

### CODE REVIEW

File: include/sparrow_extensions/fixed_shape_tensor.hpp [hunk 1]
```diff
@@ -0,0 +1,371 @@
...
+            std::optional<std::string_view> name,
+            std::optional<METADATA_RANGE> arrow_metadata = std::nullopt
+        );
+
+        // Default special members
+        fixed_shape_tensor_array(const fixed_shape_tensor_array&) = default;
+        fixed_shape_tensor_array& operator=(const fixed_shape_tensor_array&) = default;
+        fixed_shape_tensor_array(fixed_shape_tensor_array&&) noexcept = default;
+        fixed_shape_tensor_array& operator=(fixed_shape_tensor_array&&) noexcept = default;
+        ~fixed_shape_tensor_array() = default;
```
Comment (JohanMabille) [inline include/sparrow_extensions/fixed_shape_tensor.hpp]: No need to add them if they are all defaulted.

File: include/sparrow_extensions/fixed_shape_tensor.hpp [hunk 2]
```diff
@@ -0,0 +1,371 @@
...
+     *
+     * This class provides a convenient interface for working with fixed-shape tensors
+     * while maintaining compatibility with the Arrow format.
+     */
+    class SPARROW_EXTENSIONS_API fixed_shape_tensor_array
+    {
+    public:
+
+        using size_type = std::size_t;
+        using metadata_type = fixed_shape_tensor_extension::metadata;
```
Comment (JohanMabille) [inline include/sparrow_extensions/fixed_shape_tensor.hpp]: It might be worth adding inner typedefs like we have for regular arrays (value_type, const_reference, reference, iterators etc).

File: include/sparrow_extensions/fixed_shape_tensor.hpp [hunk 3]
```diff
@@ -0,0 +1,371 @@
...
+        /**
+         * @brief Access tensor at index i.
+         *
+         * @param i Index of the tensor
+         * @return A list_value representing the tensor at index i
+         *
+         * @pre i < size()
+         */
+        [[nodiscard]] auto operator[](size_type i) const
+            -> decltype(std::declval<const sparrow::fixed_sized_list_array&>()[i]);
```
Comment (JohanMabille) [inline include/sparrow_extensions/fixed_shape_tensor.hpp]: This method could return `const_reference`  if defined as an inner type.

File: include/sparrow_extensions/fixed_shape_tensor.hpp (hunk 1 above)
Comment (Alex-PLACET) [reply include/sparrow_extensions/fixed_shape_tensor.hpp]: done

**Review by JohanMabille — APPROVED** [review]

**Comment by JohanMabille** [comment]
The failure on OSX are unrelated to the changes.
